name: VS-Release
on:
  push:
    paths:
      - vs/**
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-vs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.0,17.0)'

      - name: Bump extension version
        run: ./ci/bumpVersion.ps1 "2.1.$Env:GITHUB_RUN_NUMBER"

      - name: Build extension
        run: |
          cd vs/
          msbuild DankVaporwave.csproj /t:Restore /p:Configuration=Release
          msbuild DankVaporwave.csproj /p:Configuration=Release

      - name: Archive extension artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DankVaporwave
          path: |
            bin/Release
      - name: VSIX Publisher
        run: |
          cd vs/
          $ENV:PATH="$ENV:PATH;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin"
          VsixPublisher.exe login   -publisherName JBW -personalAccessToken ${{secrets.PERSONALACCESSCODE}}
          VsixPublisher.exe publish -personalAccessToken ${{secrets.PERSONALACCESSCODE}} -payload bin/Release/DankVaporwave.vsix -publishManifest publishManifest.json
